### ISSUE TITLE
Peer review for Lab 1

### ISSUE THREAD

**Issue by federicoboscolo** [fracapuano/CompIntelligence_2022#1]
I checked the solution on my machine and it works, the results are consistent with those on README.md. The code runs very fast, in a matter of a few seconds, finding solutions up to size 1000. That is very impressive, so congrats :)

Your program uses an object oriented approach and defines many class properties, among which operators, which makes your objects very complete and organic. Exceptions are also raised in case of wrong usage, which is always nice.

All methods in the code are very well documented, following a specific format for usage, and the explanations are clear.

The code looks correct, with no redundant variables and no unnecessary loops, and it reads clearly. I couldn’t find any issues with it. 
Just one small thing I noticed: in the `heuristic` method of class `SolvedProblem` you use your flatten method on the state, however you don’t actually use that for calculations. It might be part of an unused piece of code, but I thought I’d bring it to your attention.

All in all, great solution! I’m looking forward to seeing your implementations of other priority functions and see how they compare to this one in terms of performance.

**Comment by fracapuano** [comment]
Thank you very much for your feedback! 
Let me clarify one small thing:

> Just one small thing I noticed: in the heuristic method of class SolvedProblem you use your flatten method on the state, however you don’t actually use that for calculations. It might be part of an unused piece of code, but I thought I’d bring it to your attention.

In `heuristic`, the `flatten` method is developed (but not used), you are right. 
This is because we (@mttmtt31 and I) foresee to use `heuristic` in other priority functions to select elements in the frontier. 

All in all, thank you very much for your analysis 😊
